#启动配置参数
server:
  #端口号
  port: 8083
  #项目名，如果不设定，默认是 /
  context-path: /

#spring:
#  #mysql 数据库
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/script_20220124_bishe?useUnicode=true&characterEncoding=utf-8&useSSL=true
#      username: root
#      password: 123
#
#
##mybatis配置
#mybatis:
#  mapper-locations: classpath:/mapping/**/*.xml
#  configuration:
#    lazy-load-trigger-methods: clone
#    aggressive-lazy-loading: false
#    lazy-loading-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'


