#启动配置参数
server:
  #端口号
  port: 8080
  #项目名，如果不设定，默认是 /
  context-path: /

# MVC 视图配置、静态资源位置
spring:
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**
    resources:
      static-locations: classpath:/static/